CREATE TABLE
    GRASSLAND
    (
        ID IDENTITY NOT NULL PRIMARY KEY,
        NAME VARCHAR(255) NOT NULL,
        COUNTRY VARCHAR(255) NOT NULL,
		LATITUDE VARCHAR(255) NOT NULL,
		LONGITUDE VARCHAR(255) NOT NULL
    );
	
CREATE TABLE
    UNICORN
    (
        ID IDENTITY NOT NULL PRIMARY KEY,
        NAME VARCHAR(55) NOT NULL,
		GENDER VARCHAR(25) NOT NULL,
		BIRTHDATE DATETIME NOT NULL,
        GRASSLAND_ID INTEGER NOT NULL UNIQUE,
		CONSTRAINT fk_grassland FOREIGN KEY (GRASSLAND_ID) REFERENCES GRASSLAND(ID)
    );
